---
- name: Install prerequisites packages for (apt)
  package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-utils
    - python3-venv
    - python3-dev
    - libpq-dev
    - git
    - docker.io
    - ansible
    - curl
    - nano
    - whois
    - tree
    - p7zip-full
    - postgresql-client
    - unzip
  when:
    - ansible_distribution in apt_distributions

- name: Add Docker repository for yum-based distributions
  when: ansible_distribution in yum_distributions
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install prerequisites packages (yum)
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - git
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - nano
    - curl
    - ansible
    - expect
    - whois
    - firewalld
    - tree
    - p7zip
    - postgresql
    - unzip
  when: ansible_distribution in yum_distributions

- name: Create symbolic link from 7za to 7z
  when: ansible_distribution in yum_distributions
  become: yes
  file:
    src: /usr/bin/7za
    dest: /usr/bin/7z
    state: link

- name: Get Kubernetes stable release version
  shell: "curl -L -s https://dl.k8s.io/release/stable.txt"
  register: k8s_version

- name: Download kubectl
  get_url:
    url: https://dl.k8s.io/release/{{ k8s_version.stdout }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'  # Set executable permission

- name: Set executable permission for kubectl
  file:
    path: /usr/local/bin/kubectl
    mode: '+x'

- name: Create directory for Docker Compose
  file:
    path: ~/.docker/cli-plugins/
    state: directory

- name: Download Docker Compose binary
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64
    dest: ~/.docker/cli-plugins/docker-compose
    mode: '0755'

- name: Ensure Docker Compose is executable
  command: chmod +x ~/.docker/cli-plugins/docker-compose

- name: Verify Docker Compose installation
  command: ~/.docker/cli-plugins/docker-compose --version
  register: compose_version
  changed_when: false

- name: Display Docker Compose version
  debug:
    var: compose_version.stdout_lines

- name: Start Docker service
  service:
    name: docker
    enabled: yes
    state: started
...
